##########################################################
#                                                        #
#  Docker Compose .YAML-fil for Odin/TrueNAS-server       #
#                                                        #
#  Inneholder:                                           #
#  - qBittorrent                                         #
#  - Gluetun                                             #
#                                                        #
##########################################################

# Networks, Start of ----------------------------------- #
networks:
  odin-mediastack:
    name: odin-mediastack
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET:?err}
        gateway: ${DOCKER_GATEWAY:?err}
# Networks, End of -------------------------------------- #

services:

# Gluetun, Start of ------------------------------------- #
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8888:8888/tcp"                                                   # Gluetun Local Network HTTP proxy
      - "8388:8388/tcp"                                                   # Gluetun Local Network Shadowsocks
      - "8388:8388/udp"                                                   # Gluetun Local Network Shadowsocks
      - "${WEBUI_PORT_QBITTORRENT:?err}:${WEBUI_PORT_QBITTORRENT:?err}"   # WebUI Portal: qBittorrent
      - "${QBIT_PORT_TCP:?err}:6881/tcp"                                  # qBittorrent Torrent Port TCP
      - "${QBIT_PORT_UDP:?err}:6881/udp"                                  # qBittorrent Torrent Port UDP
    volumes:
      - ${FOLDER_FOR_DATA:?err}/gluetun:/gluetun
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?err}
      - FIREWALL_OUTBOUND_SUBNETS=${LOCAL_SUBNET:?err}
      - OPENVPN_USER=${VPN_USERNAME:?err}
      - OPENVPN_PASSWORD=${VPN_PASSWORD:?err}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - VPN_TYPE=${VPN_TYPE}
    networks:
      - odin-mediastack
# Gluetun, End of --------------------------------------- #

# qBittorrent, Start of --------------------------------- #
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DATA:?err}/qbittorrent:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - WEBUI_PORT=${WEBUI_PORT_QBITTORRENT:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=${TP_THEME:?err}
    network_mode: "service:gluetun"                                      # Do NOT edit
# qBittorrent, End of ----------------------------------- #
